---
language: python
python:
  - "3.7"
os: linux
dist: jammy

# Other artifact details are accessible via Travis website
# as environment variables

# Install basic Tex Live, additional TeX packages, and Python packages.
install:
  - "sudo ./texsetup.sh"
  - "PATH=$PATH:/usr/local/texlive/2018/bin/x86_64-linux"
  - "pip install -r requirements.txt"

# Execute linting tests before running the main playbook.
# Note: "chktex" apparently always returns rc=0
# draft-mode will not render images, and provides detailed fail log
before_script:
  - "make lint"
  - "make draft"

# Make the PDF itself, including images. Usee pass2 to avoid
# trying to "open" a PDF within the CI system
script:
  - "make pass2"

after_success:
  - "python ./upload.py"
...