---
language: python
python:
  - "3.7"
os: linux
dist: jammy

# Other artifact details are accessible via Travis website
# as environment variables

# Install basic Tex Live, additional TeX packages, and Python packages.
install:

# Execute linting tests before running the main playbook.
# Note: "chktex" apparently always returns rc=0
# draft-mode will not render images, and provides detailed fail log
before_script:

# Make the PDF itself, including images. Usee pass2 to avoid
# trying to "open" a PDF within the CI system
script:

after_success:
  - "python upload.py"
...